# Generated by Django 3.2.13 on 2022-07-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='New', max_length=20),
        ),
    ]
