# Generated by Django 3.2.13 on 2022-08-29 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0002_forfeititem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForfeitItem',
            new_name='Forfeit',
        ),
    ]
