# Generated by Django 3.2.13 on 2022-07-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0002_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
