# Generated by Django 3.2.13 on 2022-07-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0003_alter_transaction_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
    ]
