# Generated by Django 3.2.13 on 2022-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0003_auto_20220719_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
