# Generated by Django 3.2.13 on 2022-07-12 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0005_auto_20220712_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_pawned',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='redeem_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
